module.exports = {
  e1: { category: "Biphasic", chart: "https://napchart.com/bqbj1" },
  segmented: { category: "Biphasic", chart: "https://napchart.com/75e40" },
  siesta: { category: "Biphasic", chart: "https://napchart.com/z9gqx" },
  e2: { category: "Everyman", chart: "https://napchart.com/bxi17" },
  e3: { category: "Everyman", chart: "https://napchart.com/lli4y" },
  e4: { category: "Everyman", chart: "https://napchart.com/kr5e8" },
  e5: { category: "Everyman", chart: "https://napchart.com/zn4h6" },
  trimaxion: { category: "Everyman", chart: "https://napchart.com/ey08s" },
  bimaxion: { category: "Everyman", chart: "https://napchart.com/r8zi1" },
  dc1: { category: "Dual Core", chart: "https://napchart.com/sbagf" },
  dc2: { category: "Dual Core", chart: "https://napchart.com/lhh7z" },
  dc3: { category: "Dual Core", chart: "https://napchart.com/qwjad" },
  dc4: { category: "Dual Core", chart: "https://napchart.com/g0jw8" },
  tc1: { category: "Tri Core", chart: "https://napchart.com/z1h8k" },
  tc2: { category: "Tri Core", chart: "https://napchart.com/1kppy" },
  triphasic: { category: "Tri Core", chart: "https://napchart.com/ekcdp" },
  mono: { category: "Monophasic", chart: "https://napchart.com/hdmmp" },
  sevamayl: { category: "Experimental", chart: "https://napchart.com/f10fn" },
  dymaxion: { category: "Nap only", chart: "https://napchart.com/90oo4" },
  naptation: { category: "Nap only", chart: "https://napchart.com/76b7u" },
  spamayl: { category: "Nap only", chart: "https://napchart.com/d6oef" },
  tesla: { category: "Nap only", chart: "https://napchart.com/a62hi" },
  uberman: { category: "Nap only", chart: "https://napchart.com/t4pyp" },
  random: { category: "Random", chart: "" }
};
