module.exports = {
	e1: { name: "E1", category: "Biphasic", chart: "https://napchart.com/bqbj1" },
	segmented: { name: "Segmented", category: "Biphasic", chart: "https://napchart.com/75e40" },
	siesta: { name: "Siesta", category: "Biphasic", chart: "https://napchart.com/z9gqx" },
	e2: { name: "E2", category: "Everyman", chart: "https://napchart.com/bxi17" },
	e3: { name: "E3", category: "Everyman", chart: "https://napchart.com/lli4y" },
	e4: { name: "E4", category: "Everyman", chart: "https://napchart.com/kr5e8" },
	e5: { name: "E5", category: "Everyman", chart: "https://napchart.com/zn4h6" },
	trimaxion: { name: "Trimaxion", category: "Everyman", chart: "https://napchart.com/ey08s" },
	bimaxion: { name: "Bimaxion", category: "Everyman", chart: "https://napchart.com/r8zi1" },
	dc1: { name: "DC1", category: "Dual Core", chart: "https://napchart.com/sbagf" },
	dc2: { name: "DC2", category: "Dual Core", chart: "https://napchart.com/lhh7z" },
	dc3: { name: "DC3", category: "Dual Core", chart: "https://napchart.com/qwjad" },
	dc4: { name: "DC4", category: "Dual Core", chart: "https://napchart.com/g0jw8" },
	tc1: { name: "TC1", category: "Tri Core", chart: "https://napchart.com/z1h8k" },
	tc2: { name: "TC2", category: "Tri Core", chart: "https://napchart.com/1kppy" },
	triphasic: { name: "Triphasic", category: "Tri Core", chart: "https://napchart.com/ekcdp" },
	mono: { name: "Mono", category: "Monophasic", chart: "https://napchart.com/hdmmp" },
	sevamayl: { name: "SEVAMAYL", category: "Experimental", chart: "https://napchart.com/f10fn" },
	dymaxion: { name: "Dymaxion", category: "Nap only", chart: "https://napchart.com/90oo4" },
	naptation: { name: "Naptation", category: "Nap only", chart: "https://napchart.com/76b7u" },
	spamayl: { name: "SPAMAYL", category: "Nap only", chart: "https://napchart.com/d6oef" },
	tesla: { name: "Tesla", category: "Nap only", chart: "https://napchart.com/a62hi" },
	uberman: { name: "Uberman", category: "Nap only", chart: "https://napchart.com/t4pyp" },
	random: { name: "Random", category: "Random", chart: "" }
};
